### ISSUE TITLE
Error msg in terminal 

### ISSUE THREAD

**Issue by 888iee** [jthistle/SUDO#10]
Great Work!
But after running the install.sh an error pops up in every terminal 
`ls: Zugriff auf '/snap/bin' nicht möglich: Datei oder Verzeichnis nicht gefunden`
This basically means `Access on /snap/bin is not possible: File or Directory not found.`
I couldn't figure out where this comes from since /snap/bin isn't mentioned anywhere in my bashrc file

**Comment by jthistle** [comment]
interessant... It's in your `$PATH`, which is being parsed in your bashrc. The code tries to `ls /snap/bin` at some point, because it's in your path. I'll add a check in the script to check if access is possible to avoid printing this error message every time.

Vielen Dank fuer die Meldung :)

**Comment by 888iee** [comment]
After deleting the SUDO part inside the .bashrc file, I cloned your repo again and installed it and still  get the same error. :(

**Comment by jthistle** [comment]
Yeah, my fix didn't work. I'll look into it more when I can, sorry.

**Comment by jthistle** [comment]
Should be fixed by 77bc68
