### ISSUE TITLE
Add an alias for SUDO

### ISSUE THREAD

**Issue by jthistle** [jthistle/SUDO#2]
This should run the last command with `sudo` prefixed, and aptly expresses the frustration felt when forgetting to prefix sudo.

**Comment by Mindavi** [comment]
alias SUDO="sudo !!"

**Comment by Mindavi** [comment]
Pretty sure you wanted to close #3 instead of this one.

**Comment by jthistle** [comment]
Yep, correct. Reopening. Feel free to open a PR, btw @Mindavi :)
